spring:
  application:
    name: backend\
  datasource:
    url: jdbc:mysql://localhost:3306/virtual_experiment?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: linyuhong1016
server:
  port: 8080
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印SQL
  type-handlers-package: com.example.experiment.handler
